"use client";

export interface PrintColumn {
  header: string;
  key: string;
  align?: "left" | "right";
}

export interface PrintPayload {
  reportTitle: string;
  periodLabel: string;
  columns: PrintColumn[];
  rows: Record<string, string | number>[];
  summaryCards?: { label: string; value: string | number }[];
  note?: string;
}

export default function PrintableReport({ payload }: { payload: PrintPayload | null }) {
  if (!payload) return null;

  const generatedAt = new Date().toLocaleString("en-GB", {
    dateStyle: "medium",
    timeStyle: "short",
  });

  return (
    <div className="hidden print:block fixed inset-0 bg-white z-99999 p-10 overflow-visible">
      <div className="max-w-5xl mx-auto">
        <div className="flex items-start justify-between border-b-2 border-gray-800 pb-4 mb-6">
          <div>
            <p className="text-xs font-bold uppercase tracking-widest text-gray-500">
              State Health Reporting
            </p>
            <h1 className="text-2xl font-bold text-gray-900 mt-1">{payload.reportTitle}</h1>
          </div>
          <div className="text-right text-xs text-gray-500 shrink-0">
            <p>Period: {payload.periodLabel}</p>
            <p>Generated: {generatedAt}</p>
          </div>
        </div>

        {payload.summaryCards && payload.summaryCards.length > 0 && (
          <div className="grid grid-cols-4 gap-3 mb-6">
            {payload.summaryCards.map((c) => (
              <div key={c.label} className="border border-gray-200 rounded-lg p-3">
                <p className="text-[10px] uppercase text-gray-400 font-semibold tracking-wide">
                  {c.label}
                </p>
                <p className="text-lg font-bold text-gray-900 mt-0.5">{c.value}</p>
              </div>
            ))}
          </div>
        )}

        <table className="w-full text-left border-collapse text-[11px]">
          <thead>
            <tr className="bg-gray-100 border-b border-gray-300">
              {payload.columns.map((col) => (
                <th
                  key={col.key}
                  className={`p-2 font-semibold text-gray-700 border-r border-gray-200 last:border-r-0 ${
                    col.align === "right" ? "text-right" : "text-left"
                  }`}
                >
                  {col.header}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {payload.rows.map((row, idx) => (
              <tr key={idx} className="border-b border-gray-200 break-inside-avoid">
                {payload.columns.map((col) => (
                  <td
                    key={col.key}
                    className={`p-2 border-r border-gray-100 last:border-r-0 ${
                      col.align === "right" ? "text-right" : "text-left"
                    }`}
                  >
                    {row[col.key] ?? "—"}
                  </td>
                ))}
              </tr>
            ))}
            {payload.rows.length === 0 && (
              <tr>
                <td colSpan={payload.columns.length} className="p-6 text-center text-gray-400">
                  No records found for this period.
                </td>
              </tr>
            )}
          </tbody>
        </table>

        {payload.note && <p className="text-[10px] text-gray-400 mt-4 italic">{payload.note}</p>}

        <p className="text-[10px] text-gray-400 mt-8 pt-3 border-t border-gray-200">
          Generated by the PHC platform · {payload.rows.length} record
          {payload.rows.length === 1 ? "" : "s"}
        </p>
      </div>
    </div>
  );
}
